# Dependencies
highlighter:      rouge
theme:  minima

# Setup
title:            Zishuo Li
tagline:          'Researcher'
description:      'I am a PhD Candidate at Tsinghua University, China.'
url:              https://zs-li.github.io/
baseurl:          'https://zs-li.github.io/'
cover_image: /public/pic.jpg

author:
name:           'Zishuo Li'
email:            lizs19@mails.tsinghua.edu.cn

paginate:         5
paginate_path:    "/notes/page:num"

# List of Pages

pages_list:
  - name: Publication
    loc: /publication.html
  - name: Research
    loc: /research.html
  - name: Talk
    loc: /talk
  - name: Notes
    loc: /notes

# Chinese Support
# Must change the cn_font_family and cn_css
# Right now it only contains the chinese characters of my name!!!
# To select font, go to: http://www.youziku.com/Home/FontSelect
# or you can remove the title_cn attribute

#title_cn:
cn_font_family: minijianxixingkai351678
cn_css: http://www.youziku.com/webfont/CSS/15f8f8252e25142e32cc295517e8a5f0

# Google font server
google_font_server: fonts.useso.com # 360 server for mainland China readers.

# In case you do not care about Chinese readers, use the default google server
# google_font_server: fonts.googleapis.com

plugins:
        - jekyll-paginate
